version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn clean install org.pitest:pitest-maven:mutationCoverage
      - store_test_results:
          path: target/pit-reports
