version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
      - run: mvn clean install org.pitest:pitest-maven:mutationCoverage
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/pit-reports

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud